name: docker build & aws ecr push

on: push
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for China region audience
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{secrets.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_ACCESS_ROLE}}

      - run: |
          aws configure list